name       : libktorrent
version    : 20.12.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/libktorrent-20.12.3.tar.xz : c31e083cf551e9b51a0641177469da6419c67182f61e4d1f2a000e7ef2767efa
license    : GPL-2.0-or-later
component  : programming.library
summary    : BitTorrent protocol implementation
description: |
    libkTorrent is a BitTorrent protocol implementation for KDE.
builddeps  :
    - pkgconfig(qca2-qt5)
    - karchive-devel
    - kcrash-devel
    - kio-devel
    - libboost-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
