name       : libktorrent
version    : 21.12.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/libktorrent-21.12.1.tar.xz : fbb57cdb079c93e70f12c1ccdd135d9989c5a7f15dc2043d09a1bbecaee77309
license    : GPL-2.0-or-later
component  : programming.library
summary    : BitTorrent protocol implementation
description: |
    libkTorrent is a BitTorrent protocol implementation for KDE.
builddeps  :
    - pkgconfig(qca2-qt5)
    - karchive-devel
    - kcrash-devel
    - kio-devel
    - libboost-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
