name       : libktorrent
version    : 23.04.3
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/libktorrent-23.04.3.tar.xz : 4bf1ca829fc125aedd765bd225569189a971b063cf40c753c647b7b8c2f4cfd4
license    : GPL-2.0-or-later
component  : programming.library
summary    : BitTorrent protocol implementation
description: |
    libkTorrent is a BitTorrent protocol implementation for KDE.
builddeps  :
    - pkgconfig(qca2-qt5)
    - karchive-devel
    - kcrash-devel
    - kio-devel
    - libboost-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
