name       : libktorrent
version    : 21.08.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/libktorrent-21.08.3.tar.xz : a666d7c36fe4f6a8f960afb6605cd4c7aac5cb8048e41c8c8b6957d060b756fe
license    : GPL-2.0-or-later
component  : programming.library
summary    : BitTorrent protocol implementation
description: |
    libkTorrent is a BitTorrent protocol implementation for KDE.
builddeps  :
    - pkgconfig(qca2-qt5)
    - karchive-devel
    - kcrash-devel
    - kio-devel
    - libboost-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
