name       : libktorrent
version    : 2.1
release    : 2
source     :
    - https://cdn.download.kde.org/stable/ktorrent/5.1/libktorrent-2.1.tar.xz : 3eefdcceec73410c558e82d7be22eb2ed18679e9ab64f34cc100b54e186fe26f
license    : GPL-2.0
component  : programming.library
summary    : BitTorrent protocol implementation
description: |
    libkTorrent is a BitTorrent protocol implementation for KDE.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - ki18n-devel
    - kio-devel
    - libboost-devel
    - libgcrypt-devel
    - solid-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
