name       : libktorrent
version    : 22.04.1
release    : 24
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/libktorrent-22.04.1.tar.xz : 57dd46edc9e10127bca69104b0288bdfa5f1dab261f89d8fa4b2161ab7e7ddca
license    : GPL-2.0-or-later
component  : programming.library
summary    : BitTorrent protocol implementation
description: |
    libkTorrent is a BitTorrent protocol implementation for KDE.
builddeps  :
    - pkgconfig(qca2-qt5)
    - karchive-devel
    - kcrash-devel
    - kio-devel
    - libboost-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
